### ISSUE TITLE
你好 大佬  我有个事情需要向您咨询一下

### ISSUE THREAD

**Issue by liuyuqingenglish** [autulin/SpareTire#1]
你好 大佬  我有个事情需要向您咨询一下，关于gb28181 推流的问题，之前下载了您的一个gb28181的源码，但是推流的时候一直卡死 崩溃，可以要一下您的联系方式么，

**Comment by autulin** [comment]
你好，不好意思，那个工程版权属于单位，且我已不再维护，所以下掉了，有问题只能你们自己查了哦。

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
发件人: liuyuqingenglish <notifications@github.com>
发送时间: 星期四, 三月 21, 2019 10:12
收件人: autulin/SpareTire
抄送: Subscribed
主题: [autulin/SpareTire] 你好 大佬 我有个事情需要向您咨询一下 (#1)


你好 大佬 我有个事情需要向您咨询一下，关于gb28181 推流的问题，之前下载了您的一个gb28181的源码，但是推流的时候一直卡死 崩溃，可以要一下您的联系方式么，

―

**Comment by liuyuqingenglish** [comment]
能给个联系方式么，我和您私聊一下

**Comment by autulin** [comment]
不确定能否解决你的问题，可以加我qq：136137845

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
发件人: liuyuqingenglish <notifications@github.com>
发送时间: 星期四, 三月 21, 2019 10:20
收件人: autulin/SpareTire
抄送: autulin; Comment
主题: Re: [autulin/SpareTire] 你好 大佬 我有个事情需要向您咨询一下 (#1)


能给个联系方式么，我和您私聊一下

―

**Comment by liuyuqingenglish** [comment]
好的 谢谢
